Repository 18F/18f.gsa.gov, pull requests merged in 2021-03, with the labels that each got.

#3362 Create Posts “2021-03-02-using-agile-and-devops-to-get-better-results-than-a-change-control-board”
  _posts/2021-03-02-using-agile-and-devops-to-get-better-results-than-a-change-control-board.md
  assets/blog/image1.png
  assets/blog/image2.png
  assets/blog/image3.png
Labels: netlify-cms/draft

#3351 update cards to USWDS
  _includes/card-project.html
  _includes/card.html
  _layouts/hww-primary.html
  _sass/_components/card.scss
  _sass/_uswds-theme-custom-styles.scss
  pages/home.html
  pages/what-we-deliver.md
Labels: migrate to uswds-jekyll

#3363 Fix js by removing all not from theme
  _config.yml
  assets/js/external-links.js
  assets/js/index.js
  assets/js/jquery.min.js
  assets/js/sticky.js
  assets/js/waypoints.js
  assets/js/waypoints.min.js
Labels: migrate to uswds-jekyll

#3358 update most tests
  _config.yml
  _plugins/README.md
  _plugins/markdown.rb
  _plugins/team.rb
  assets/js/external-links.js
  assets/js/index.js
  assets/js/jquery.min.js
  assets/js/sticky.js
  assets/js/waypoints.js
  assets/js/waypoints.min.js
  pages/contact.md
  spec/_authors/author.md
  spec/_authors/author_with_content.md
  spec/_plugins/team_spec.rb
  spec/spec_helper.rb
Labels: migrate to uswds-jekyll

#3370 Create Authors “andrew-dunkman”
  _authors/andrew-dunkman.md
Labels: netlify-cms/pending_publish

#3371 Create Authors “heather-battaglia”
  _authors/heather-battaglia.md
Labels: netlify-cms/pending_publish

#3369 Create Posts “2021-03-05-technical-problems-are-not-the-hardest-ones-to-solve”
  _posts/2021-03-05-technical-problems-are-not-the-hardest-ones-to-solve.md
Labels: netlify-cms/pending_review

#3380 Design review remediations: guides
  _includes/banner-cta.html
  _includes/footer.html
  _includes/navigation/footer-desktop.html
  _layouts/default-profile.html
  _layouts/hww-primary.html
  _layouts/primary.html
  _layouts/project-page.html
  _layouts/tag-results.html
  _sass/_components/blockquotes.scss
  _sass/_components/blog-index.scss
  _sass/_components/blog-pagination.scss
  _sass/_components/card.scss
  _sass/_components/figure.scss
  _sass/_components/post-feature.scss
  _sass/_components/post-meta.scss
  _sass/_components/post-pagination.scss
  _sass/_components/section-info.scss
  _sass/_styleguide/color-box.scss
  _sass/_styleguide/layout.scss
  _sass/_styleguide/typography.scss
  _sass/_templates/guides.scss
  _sass/_templates/home.scss
  _sass/_theme/_uswds-theme-color.scss
  _sass/_uswds-theme-custom-styles.scss
  blog/index.html
  pages/guides.md
  pages/home.html
Labels: Design Review, migrate to uswds-jekyll

#3382 Footer/ WWD/ Contact Page: design review tweaks
  .scss-lint.yml
  README.md
  _data/featured_blog_content.yml
  _includes/banner-cta.html
  _includes/testimonial.html
  _layouts/primary.html
  _layouts/project-page.html
  _sass/_components/blockquotes.scss
  _sass/_components/card.scss
  _sass/_components/lists.scss
  _sass/_components/post-feature.scss
  _sass/_print/all.scss
  _sass/_print/blog.scss
  _sass/_print/contact.scss
  _sass/_print/how-we-work.scss
  _sass/_print/what-we-deliver.scss
  _sass/_styleguide/all.scss
  _sass/_styleguide/typography.scss
  _sass/_templates/how-we-work.scss
  _sass/_templates/what-we-deliver.scss
  _sass/_theme/_uswds-theme-components.scss
  _sass/_uswds-theme-custom-styles.scss
  admin/config.yml
  assets/img/logos/agencies/treasury.svg
  assets/img/tablet-hand--c.svg
  blog/index.html
  pages/contact.md
  pages/home.html
  pages/how-we-work.md
  pages/what-we-deliver.md
Labels: Design Review, migrate to uswds-jekyll

#3386 Project page: design review remediation & styleguide trimming
  _includes/banner.html
  _includes/post.html
  _includes/side-cta.html
  _layouts/project-page.html
  _products_projects/cloud-gov.md
  _products_projects/eregs.md
  _products_projects/federalist.md
  _products_projects/login-gov.md
  _products_projects/micro-purchase-marketplace.md
  _sass/_components/lists.scss
  _sass/_components/post-feature.scss
  _sass/_styleguide/all.scss
  _sass/_styleguide/color-box.scss
  _sass/_styleguide/layout.scss
  _sass/_styleguide/nav.scss
  _sass/_templates/guides.scss
  _sass/_templates/what-we-deliver.scss
  _sass/_uswds-theme-custom-styles.scss
  _services_projects/alaska-dhss.md
  _services_projects/c2.md
  _services_projects/calc.md
  _services_projects/dhs-myuscis.md
  _services_projects/dod-military-onesource.md
  _services_projects/doi-every-kid-in-a-park.md
  _services_projects/doi-nrrd.md
  _services_projects/doj-crt-portal.md
  _services_projects/dol-wage-and-hour.md
  _services_projects/ed-college-scorecard.md
  _services_projects/fbi-crime-data-explorer.md
  _services_projects/fec-gov.md
  _services_projects/forest-service.md
  _services_projects/hhs-states.md
  _services_projects/navy-reserve.md
  _services_projects/nsf-brand-principles-project-page.md
  _services_projects/nsf-seedfund.md
  _services_projects/state-uskpa.md
  _services_projects/treasury-data-act.md
  _services_projects/treasury-new-ten.md
  _services_projects/us-web-design-standards.md
  examples/project-template.md
  pages/what-we-deliver.md
Labels: Design Review, migrate to uswds-jekyll

#3383 Header nav DR
  _config.yml
  _data/theme.yml
  _includes/components/header.html
  _includes/header.html
  _sass/_components/header.scss
  _sass/_components/nav-buttons.scss
  _sass/_theme/_uswds-theme-components.scss
  _sass/_uswds-theme-custom-styles.scss
Labels: Design Review, migrate to uswds-jekyll

#3424 Create Posts “2021-03-31-18f-public-benefits-portfolio-reflects-on-the-last-year”
  _posts/2021-03-31-18f-public-benefits-portfolio-reflects-on-the-last-year.md
  assets/blog/ak-apd-homepage.png
Labels: netlify-cms/pending_publish
